### ISSUE TITLE
cli args checking is wrong

### ISSUE THREAD

**Issue by louridas** [milouk/DigiSign#2]
Line:

https://github.com/milouk/DigiSign/blob/3397ab3cf3e0fc24e8229bfbe8ddefba10dc8af0/src/main/java/com/milouk/digisign/CreateSignature.java#L127

is wrong.

You probably want:

if (cmd.hasOption("h") || cmd.getOptions().length == 0)

**Comment by milouk** [comment]
Thanks. 

0c9eb45a475ab2199db14e7bfb90f19ef3699c5f fixes it
